# install with `pre-commit install --hook-type commit-msg`

repos:
  - repo: local
    hooks:
      - id: needs-prefix
        name: commit message needs to have a prefix
        language: pygrep
        entry: '^(chore|test|feat|fix|build|docs|refactor)!?(\([a-z]+\))?: (?![A-Z])(?![a-z]+(ed|ing)\s).*$'
        args:
          - '--multiline'
          - '--negate'
        stages:
          - commit-msg
  - repo: 'https://github.com/astral-sh/ruff-pre-commit'
    rev: v0.6.8
    hooks:
      - id: ruff
