name: Static code analysis

on:
  push:
    branches:
      - "**"

env:
  RUFF_VERSION: "0.5.1"
  MYPY_VERSION: "1.11.2"

jobs:
  ruff:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install ruff
        run: python -m pip install ruff==$RUFF_VERSION

      - name: Run ruff
        run: python -m ruff check .

  mypy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install mypy
        run: python -m pip install mypy==$MYPY_VERSION

      - name: Install mypy
        run: python -m pip install -r requirements/typing.txt

      - name: Run mypy
        run: python -m mypy .
